/* 
 * vpn
 *
 * This module defines the YANG model for Nova IPv4 VPN services. The model can be used to create a swagger API definition using the yanger tool.Written by Jon Beasley - WAN Architecture and Strategy - 2018
 *
 * OpenAPI spec version: 1.0.0.1
 * Contact: jonathan.beasley@refinitiv.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.NovaVpnSwagger.Api;
using IO.NovaVpnSwagger.Model;
using IO.NovaVpnSwagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.NovaVpnSwagger.Test
{
    /// <summary>
    ///  Class for testing RootIetfrestconfrestconf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RootIetfrestconfrestconfTests
    {
        // TODO uncomment below to declare an instance variable for RootIetfrestconfrestconf
        //private RootIetfrestconfrestconf instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RootIetfrestconfrestconf
            //instance = new RootIetfrestconfrestconf();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RootIetfrestconfrestconf
        /// </summary>
        [Test]
        public void RootIetfrestconfrestconfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RootIetfrestconfrestconf
            //Assert.IsInstanceOfType<RootIetfrestconfrestconf> (instance, "variable 'instance' is a RootIetfrestconfrestconf");
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'Operations'
        /// </summary>
        [Test]
        public void OperationsTest()
        {
            // TODO unit test for the property 'Operations'
        }
        /// <summary>
        /// Test the property 'YangLibraryVersion'
        /// </summary>
        [Test]
        public void YangLibraryVersionTest()
        {
            // TODO unit test for the property 'YangLibraryVersion'
        }

    }

}
