/* 
 * vpn
 *
 * This module defines the YANG model for Nova IPv4 VPN services. The model can be used to create a swagger API definition using the yanger tool.Written by Jon Beasley - WAN Architecture and Strategy - 2018
 *
 * OpenAPI spec version: 1.0.0.1
 * Contact: jonathan.beasley@refinitiv.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.NovaVpnSwagger.Client.SwaggerDateConverter;

namespace IO.NovaVpnSwagger.Model
{
    /// <summary>
    /// IPv4 outbound routing policy. (non-presence)
    /// </summary>
    [DataContract]
    public partial class DataVpnIpv4inboundroutingpolicyVpnipv4inboundroutingpolicy :  IEquatable<DataVpnIpv4inboundroutingpolicyVpnipv4inboundroutingpolicy>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DataVpnIpv4inboundroutingpolicyVpnipv4inboundroutingpolicy" /> class.
        /// </summary>
        /// <param name="tenantIpv4Prefix">List of IPv4 prefixes for routes towards Tenant Networks. (list).</param>
        /// <param name="tenantCommunity">List of BGP communities for routes towards Tenant Networks. (list).</param>
        public DataVpnIpv4inboundroutingpolicyVpnipv4inboundroutingpolicy(List<DataVpnIpv4inboundroutingpolicyTenantipv4prefixTenantipv4prefixprefixVpntenantipv4prefix> tenantIpv4Prefix = default(List<DataVpnIpv4inboundroutingpolicyTenantipv4prefixTenantipv4prefixprefixVpntenantipv4prefix>), List<DataVpnIpv4inboundroutingpolicyTenantcommunityTenantcommunityautonomoussystemnumberTenantcommunitynumberVpntenantcommunity> tenantCommunity = default(List<DataVpnIpv4inboundroutingpolicyTenantcommunityTenantcommunityautonomoussystemnumberTenantcommunitynumberVpntenantcommunity>))
        {
            this.TenantIpv4Prefix = tenantIpv4Prefix;
            this.TenantCommunity = tenantCommunity;
        }
        
        /// <summary>
        /// List of IPv4 prefixes for routes towards Tenant Networks. (list)
        /// </summary>
        /// <value>List of IPv4 prefixes for routes towards Tenant Networks. (list)</value>
        [DataMember(Name="tenant-ipv4-prefix", EmitDefaultValue=false)]
        public List<DataVpnIpv4inboundroutingpolicyTenantipv4prefixTenantipv4prefixprefixVpntenantipv4prefix> TenantIpv4Prefix { get; set; }

        /// <summary>
        /// List of BGP communities for routes towards Tenant Networks. (list)
        /// </summary>
        /// <value>List of BGP communities for routes towards Tenant Networks. (list)</value>
        [DataMember(Name="tenant-community", EmitDefaultValue=false)]
        public List<DataVpnIpv4inboundroutingpolicyTenantcommunityTenantcommunityautonomoussystemnumberTenantcommunitynumberVpntenantcommunity> TenantCommunity { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DataVpnIpv4inboundroutingpolicyVpnipv4inboundroutingpolicy {\n");
            sb.Append("  TenantIpv4Prefix: ").Append(TenantIpv4Prefix).Append("\n");
            sb.Append("  TenantCommunity: ").Append(TenantCommunity).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DataVpnIpv4inboundroutingpolicyVpnipv4inboundroutingpolicy);
        }

        /// <summary>
        /// Returns true if DataVpnIpv4inboundroutingpolicyVpnipv4inboundroutingpolicy instances are equal
        /// </summary>
        /// <param name="input">Instance of DataVpnIpv4inboundroutingpolicyVpnipv4inboundroutingpolicy to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DataVpnIpv4inboundroutingpolicyVpnipv4inboundroutingpolicy input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.TenantIpv4Prefix == input.TenantIpv4Prefix ||
                    this.TenantIpv4Prefix != null &&
                    this.TenantIpv4Prefix.SequenceEqual(input.TenantIpv4Prefix)
                ) && 
                (
                    this.TenantCommunity == input.TenantCommunity ||
                    this.TenantCommunity != null &&
                    this.TenantCommunity.SequenceEqual(input.TenantCommunity)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TenantIpv4Prefix != null)
                    hashCode = hashCode * 59 + this.TenantIpv4Prefix.GetHashCode();
                if (this.TenantCommunity != null)
                    hashCode = hashCode * 59 + this.TenantCommunity.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
