/* 
 * vpn
 *
 * This module defines the YANG model for Nova IPv4 VPN services. The model can be used to create a swagger API definition using the yanger tool.Written by Jon Beasley - WAN Architecture and Strategy - 2018
 *
 * OpenAPI spec version: 1.0.0.1
 * Contact: jonathan.beasley@refinitiv.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.NovaVpnSwagger.Client.SwaggerDateConverter;

namespace IO.NovaVpnSwagger.Model
{
    /// <summary>
    /// DataVpnVpnInstanceInstanceNameTopologyType
    /// </summary>
    [DataContract]
    public partial class DataVpnVpnInstanceInstanceNameTopologyType :  IEquatable<DataVpnVpnInstanceInstanceNameTopologyType>, IValidatableObject
    {
        /// <summary>
        /// The Topology Type of the IP VPN (e.g. any-to-any) (leaf)
        /// </summary>
        /// <value>The Topology Type of the IP VPN (e.g. any-to-any) (leaf)</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum VpntopologyTypeEnum
        {
            
            /// <summary>
            /// Enum AnyToAny for value: Any-to-Any
            /// </summary>
            [EnumMember(Value = "Any-to-Any")]
            AnyToAny = 1,
            
            /// <summary>
            /// Enum HubAndSpoke for value: Hub-and-Spoke
            /// </summary>
            [EnumMember(Value = "Hub-and-Spoke")]
            HubAndSpoke = 2
        }

        /// <summary>
        /// The Topology Type of the IP VPN (e.g. any-to-any) (leaf)
        /// </summary>
        /// <value>The Topology Type of the IP VPN (e.g. any-to-any) (leaf)</value>
        [DataMember(Name="vpn:topology-type", EmitDefaultValue=false)]
        public VpntopologyTypeEnum? VpntopologyType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="DataVpnVpnInstanceInstanceNameTopologyType" /> class.
        /// </summary>
        /// <param name="vpntopologyType">The Topology Type of the IP VPN (e.g. any-to-any) (leaf) (default to VpntopologyTypeEnum.AnyToAny).</param>
        public DataVpnVpnInstanceInstanceNameTopologyType(VpntopologyTypeEnum? vpntopologyType = VpntopologyTypeEnum.AnyToAny)
        {
            // use default value if no "vpntopologyType" provided
            if (vpntopologyType == null)
            {
                this.VpntopologyType = VpntopologyTypeEnum.AnyToAny;
            }
            else
            {
                this.VpntopologyType = vpntopologyType;
            }
        }
        

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DataVpnVpnInstanceInstanceNameTopologyType {\n");
            sb.Append("  VpntopologyType: ").Append(VpntopologyType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DataVpnVpnInstanceInstanceNameTopologyType);
        }

        /// <summary>
        /// Returns true if DataVpnVpnInstanceInstanceNameTopologyType instances are equal
        /// </summary>
        /// <param name="input">Instance of DataVpnVpnInstanceInstanceNameTopologyType to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DataVpnVpnInstanceInstanceNameTopologyType input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.VpntopologyType == input.VpntopologyType ||
                    (this.VpntopologyType != null &&
                    this.VpntopologyType.Equals(input.VpntopologyType))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.VpntopologyType != null)
                    hashCode = hashCode * 59 + this.VpntopologyType.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
