/* 
 * attachment
 *
 * This module defines the YANG model for CE Attachment to a Provider Domain PE. The model code is derived from the Nova VPN architecture. This model intends to provide a device-agnostic service API towards northbound systems and therefore abstracts the details of how various types of PE attachment are configured on the network.
 *
 * OpenAPI spec version: 1.0.0.1
 * Contact: jonathan.beasley@refinitiv.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.NovaAttSwagger.Api;
using IO.NovaAttSwagger.Model;
using IO.NovaAttSwagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.NovaAttSwagger.Test
{
    /// <summary>
    ///  Class for testing DataAttachmentContractbandwidthpoolContractbandwidthpoolnameServiceclassesServiceclassesscnameAttachmentserviceclasses
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DataAttachmentContractbandwidthpoolContractbandwidthpoolnameServiceclassesServiceclassesscnameAttachmentserviceclassesTests
    {
        // TODO uncomment below to declare an instance variable for DataAttachmentContractbandwidthpoolContractbandwidthpoolnameServiceclassesServiceclassesscnameAttachmentserviceclasses
        //private DataAttachmentContractbandwidthpoolContractbandwidthpoolnameServiceclassesServiceclassesscnameAttachmentserviceclasses instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DataAttachmentContractbandwidthpoolContractbandwidthpoolnameServiceclassesServiceclassesscnameAttachmentserviceclasses
            //instance = new DataAttachmentContractbandwidthpoolContractbandwidthpoolnameServiceclassesServiceclassesscnameAttachmentserviceclasses();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DataAttachmentContractbandwidthpoolContractbandwidthpoolnameServiceclassesServiceclassesscnameAttachmentserviceclasses
        /// </summary>
        [Test]
        public void DataAttachmentContractbandwidthpoolContractbandwidthpoolnameServiceclassesServiceclassesscnameAttachmentserviceclassesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DataAttachmentContractbandwidthpoolContractbandwidthpoolnameServiceclassesServiceclassesscnameAttachmentserviceclasses
            //Assert.IsInstanceOfType<DataAttachmentContractbandwidthpoolContractbandwidthpoolnameServiceclassesServiceclassesscnameAttachmentserviceclasses> (instance, "variable 'instance' is a DataAttachmentContractbandwidthpoolContractbandwidthpoolnameServiceclassesServiceclassesscnameAttachmentserviceclasses");
        }


        /// <summary>
        /// Test the property 'ScName'
        /// </summary>
        [Test]
        public void ScNameTest()
        {
            // TODO unit test for the property 'ScName'
        }
        /// <summary>
        /// Test the property 'ScBandwidth'
        /// </summary>
        [Test]
        public void ScBandwidthTest()
        {
            // TODO unit test for the property 'ScBandwidth'
        }

    }

}
