/* 
 * attachment
 *
 * This module defines the YANG model for CE Attachment to a Provider Domain PE. The model code is derived from the Nova VPN architecture. This model intends to provide a device-agnostic service API towards northbound systems and therefore abstracts the details of how various types of PE attachment are configured on the network.
 *
 * OpenAPI spec version: 1.0.0.1
 * Contact: jonathan.beasley@refinitiv.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.NovaAttSwagger.Api;
using IO.NovaAttSwagger.Model;
using IO.NovaAttSwagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.NovaAttSwagger.Test
{
    /// <summary>
    ///  Class for testing DataAttachmentAttachmentPePepenameTaggedattachmentinterfaceTaggedattachmentinterfaceinterfacetypeTaggedattachmentinterfaceinterfaceidAttachmenttaggedattachmentinterface
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DataAttachmentAttachmentPePepenameTaggedattachmentinterfaceTaggedattachmentinterfaceinterfacetypeTaggedattachmentinterfaceinterfaceidAttachmenttaggedattachmentinterfaceTests
    {
        // TODO uncomment below to declare an instance variable for DataAttachmentAttachmentPePepenameTaggedattachmentinterfaceTaggedattachmentinterfaceinterfacetypeTaggedattachmentinterfaceinterfaceidAttachmenttaggedattachmentinterface
        //private DataAttachmentAttachmentPePepenameTaggedattachmentinterfaceTaggedattachmentinterfaceinterfacetypeTaggedattachmentinterfaceinterfaceidAttachmenttaggedattachmentinterface instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DataAttachmentAttachmentPePepenameTaggedattachmentinterfaceTaggedattachmentinterfaceinterfacetypeTaggedattachmentinterfaceinterfaceidAttachmenttaggedattachmentinterface
            //instance = new DataAttachmentAttachmentPePepenameTaggedattachmentinterfaceTaggedattachmentinterfaceinterfacetypeTaggedattachmentinterfaceinterfaceidAttachmenttaggedattachmentinterface();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DataAttachmentAttachmentPePepenameTaggedattachmentinterfaceTaggedattachmentinterfaceinterfacetypeTaggedattachmentinterfaceinterfaceidAttachmenttaggedattachmentinterface
        /// </summary>
        [Test]
        public void DataAttachmentAttachmentPePepenameTaggedattachmentinterfaceTaggedattachmentinterfaceinterfacetypeTaggedattachmentinterfaceinterfaceidAttachmenttaggedattachmentinterfaceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DataAttachmentAttachmentPePepenameTaggedattachmentinterfaceTaggedattachmentinterfaceinterfacetypeTaggedattachmentinterfaceinterfaceidAttachmenttaggedattachmentinterface
            //Assert.IsInstanceOfType<DataAttachmentAttachmentPePepenameTaggedattachmentinterfaceTaggedattachmentinterfaceinterfacetypeTaggedattachmentinterfaceinterfaceidAttachmenttaggedattachmentinterface> (instance, "variable 'instance' is a DataAttachmentAttachmentPePepenameTaggedattachmentinterfaceTaggedattachmentinterfaceinterfacetypeTaggedattachmentinterfaceinterfaceidAttachmenttaggedattachmentinterface");
        }


        /// <summary>
        /// Test the property 'InterfaceType'
        /// </summary>
        [Test]
        public void InterfaceTypeTest()
        {
            // TODO unit test for the property 'InterfaceType'
        }
        /// <summary>
        /// Test the property 'InterfaceId'
        /// </summary>
        [Test]
        public void InterfaceIdTest()
        {
            // TODO unit test for the property 'InterfaceId'
        }
        /// <summary>
        /// Test the property 'InterfaceMtu'
        /// </summary>
        [Test]
        public void InterfaceMtuTest()
        {
            // TODO unit test for the property 'InterfaceMtu'
        }
        /// <summary>
        /// Test the property 'AttachmentBandwidth'
        /// </summary>
        [Test]
        public void AttachmentBandwidthTest()
        {
            // TODO unit test for the property 'AttachmentBandwidth'
        }
        /// <summary>
        /// Test the property 'ContractBandwidthPool'
        /// </summary>
        [Test]
        public void ContractBandwidthPoolTest()
        {
            // TODO unit test for the property 'ContractBandwidthPool'
        }
        /// <summary>
        /// Test the property 'Vif'
        /// </summary>
        [Test]
        public void VifTest()
        {
            // TODO unit test for the property 'Vif'
        }

    }

}
