/* 
 * attachment
 *
 * This module defines the YANG model for CE Attachment to a Provider Domain PE. The model code is derived from the Nova VPN architecture. This model intends to provide a device-agnostic service API towards northbound systems and therefore abstracts the details of how various types of PE attachment are configured on the network.
 *
 * OpenAPI spec version: 1.0.0.1
 * Contact: jonathan.beasley@refinitiv.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.NovaAttSwagger.Api;
using IO.NovaAttSwagger.Model;
using IO.NovaAttSwagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.NovaAttSwagger.Test
{
    /// <summary>
    ///  Class for testing DataAttachmentAttachmentPePepenameVrfVrfvrfnameBgppeerBgppeerpeeripv4addressAttachmentbgppeer
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DataAttachmentAttachmentPePepenameVrfVrfvrfnameBgppeerBgppeerpeeripv4addressAttachmentbgppeerTests
    {
        // TODO uncomment below to declare an instance variable for DataAttachmentAttachmentPePepenameVrfVrfvrfnameBgppeerBgppeerpeeripv4addressAttachmentbgppeer
        //private DataAttachmentAttachmentPePepenameVrfVrfvrfnameBgppeerBgppeerpeeripv4addressAttachmentbgppeer instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DataAttachmentAttachmentPePepenameVrfVrfvrfnameBgppeerBgppeerpeeripv4addressAttachmentbgppeer
            //instance = new DataAttachmentAttachmentPePepenameVrfVrfvrfnameBgppeerBgppeerpeeripv4addressAttachmentbgppeer();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DataAttachmentAttachmentPePepenameVrfVrfvrfnameBgppeerBgppeerpeeripv4addressAttachmentbgppeer
        /// </summary>
        [Test]
        public void DataAttachmentAttachmentPePepenameVrfVrfvrfnameBgppeerBgppeerpeeripv4addressAttachmentbgppeerInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DataAttachmentAttachmentPePepenameVrfVrfvrfnameBgppeerBgppeerpeeripv4addressAttachmentbgppeer
            //Assert.IsInstanceOfType<DataAttachmentAttachmentPePepenameVrfVrfvrfnameBgppeerBgppeerpeeripv4addressAttachmentbgppeer> (instance, "variable 'instance' is a DataAttachmentAttachmentPePepenameVrfVrfvrfnameBgppeerBgppeerpeeripv4addressAttachmentbgppeer");
        }


        /// <summary>
        /// Test the property 'PeerIpv4Address'
        /// </summary>
        [Test]
        public void PeerIpv4AddressTest()
        {
            // TODO unit test for the property 'PeerIpv4Address'
        }
        /// <summary>
        /// Test the property 'PeerAutonomousSystem'
        /// </summary>
        [Test]
        public void PeerAutonomousSystemTest()
        {
            // TODO unit test for the property 'PeerAutonomousSystem'
        }
        /// <summary>
        /// Test the property 'PeerPassword'
        /// </summary>
        [Test]
        public void PeerPasswordTest()
        {
            // TODO unit test for the property 'PeerPassword'
        }
        /// <summary>
        /// Test the property 'MaxPeerRoutes'
        /// </summary>
        [Test]
        public void MaxPeerRoutesTest()
        {
            // TODO unit test for the property 'MaxPeerRoutes'
        }
        /// <summary>
        /// Test the property 'IsBfdEnabled'
        /// </summary>
        [Test]
        public void IsBfdEnabledTest()
        {
            // TODO unit test for the property 'IsBfdEnabled'
        }
        /// <summary>
        /// Test the property 'IsMultiHop'
        /// </summary>
        [Test]
        public void IsMultiHopTest()
        {
            // TODO unit test for the property 'IsMultiHop'
        }

    }

}
